{{- if .Values.runtimeClass.enabled }}
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ .Values.runtimeClass.name }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
handler: {{ .Values.runtimeClass.name }}
{{- end }}
